In [2]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
Books = pd.read_csv('/Users/raghx/Desktop/Machine learning 2/archive (23)/Books.csv')
Ratings = pd.read_csv('/Users/raghx/Desktop/Machine learning 2/archive (23)/Ratings.csv')
Users = pd.read_csv('/Users/raghx/Desktop/Machine learning 2/archive (23)/Users.csv')

/var/folders/wq/n2q2m9w17lg_p99b5c2yc2dm0000gn/T/ipykernel_15696/2399503585.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  Books = pd.read_csv('/Users/raghx/Desktop/Machine learning 2/archive (23)/Books.csv')

In [4]:
Ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [5]:
Users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [6]:
Books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [7]:
Books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 271360 non-null  object
 1   Book-Title           271360 non-null  object
 2   Book-Author          271358 non-null  object
 3   Year-Of-Publication  271360 non-null  object
 4   Publisher            271358 non-null  object
 5   Image-URL-S          271360 non-null  object
 6   Image-URL-M          271360 non-null  object
 7   Image-URL-L          271357 non-null  object
dtypes: object(8)
memory usage: 16.6+ MB

In [8]:
Books.drop(columns=['Image-URL-S','Image-URL-L'],inplace=True)

In [9]:
Books.dropna(inplace=True)
Books.drop_duplicates(inplace=True)

In [10]:
Books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            0
Year-Of-Publication    0
Publisher              0
Image-URL-M            0
dtype: int64

In [11]:
Books.info()

<class 'pandas.core.frame.DataFrame'>
Index: 271356 entries, 0 to 271359
Data columns (total 6 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 271356 non-null  object
 1   Book-Title           271356 non-null  object
 2   Book-Author          271356 non-null  object
 3   Year-Of-Publication  271356 non-null  object
 4   Publisher            271356 non-null  object
 5   Image-URL-M          271356 non-null  object
dtypes: object(6)
memory usage: 14.5+ MB

In [12]:
Ratings_with_bookinfo = Ratings.merge(Books,on='ISBN')

In [13]:
Ratings_with_bookinfo['Book-Rating'].astype(dtype=int)
Ratings_with_bookinfo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1031132 entries, 0 to 1031131
Data columns (total 8 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   User-ID              1031132 non-null  int64
 1   ISBN                 1031132 non-null  object
 2   Book-Rating          1031132 non-null  int64
 3   Book-Title           1031132 non-null  object
 4   Book-Author          1031132 non-null  object
 5   Year-Of-Publication  1031132 non-null  object
 6   Publisher            1031132 non-null  object
 7   Image-URL-M          1031132 non-null  object
dtypes: int64(2), object(6)
memory usage: 62.9+ MB

In [14]:
Rating_count = Ratings_with_bookinfo.groupby('Book-Title').count()[['Book-Rating']].reset_index()
Rating_count.rename(columns={'Book-Rating':'NumberOfRatings'},inplace=True)
Rating_count

                                               Book-Title  NumberOfRatings
0        A Light in the Storm: The Civil War Diary of ...                4
1                                   Always Have Popsicles                1
2                    Apple Magic (The Collector's series)                1
3        Ask Lily (Young Women of Faith: Lily Series, ...                1
4        Beyond IBM: Leadership Marketing and Finance ...                1
...                                                   ...              ...
241063                                      Ã?Â?lpiraten.                2
241064                     Ã?Â?rger mit Produkt X. Roman.                4
241065                                Ã?Â?sterlich leben.                1
241066                              Ã?Â?stlich der Berge.                3
241067                                  Ã?Â?thique en toc                2

[241068 rows x 2 columns]

In [15]:
Average_rating=Ratings_with_bookinfo.groupby('Book-Title')['Book-Rating'].mean().reset_index()
Average_rating.rename(columns={'Book-Rating':'AverageRating'},inplace=True)
Average_rating

                                               Book-Title  AverageRating
0        A Light in the Storm: The Civil War Diary of ...       2.250000
1                                   Always Have Popsicles       0.000000
2                    Apple Magic (The Collector's series)       0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...       8.000000
4        Beyond IBM: Leadership Marketing and Finance ...       0.000000
...                                                   ...            ...
241063                                      Ã?Â?lpiraten.       0.000000
241064                     Ã?Â?rger mit Produkt X. Roman.       5.250000
241065                                Ã?Â?sterlich leben.       7.000000
241066                              Ã?Â?stlich der Berge.       2.666667
241067                                  Ã?Â?thique en toc       4.000000

[241068 rows x 2 columns]

In [16]:
Popular_books = Rating_count.merge(Average_rating,on='Book-Title')
Popular_books

,Book-Title,NumberOfRatings,AverageRating
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241063,Ã?Â?lpiraten.,2,0.000000
241064,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241065,Ã?Â?sterlich leben.,1,7.000000
241066,Ã?Â?stlich der Berge.,3,2.666667
241067,Ã?Â?thique en toc,2,4.000000

In [17]:
Popular_books_final = Popular_books[Popular_books['NumberOfRatings'] > 200].sort_values(by='AverageRating',ascending=False).head(50)
Popular_books_final

,Book-Title,NumberOfRatings,AverageRating
80433,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80421,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80440,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
80425,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
60581,Ender's Game (Ender Wiggins Saga (Paperback)),249,5.409639
80413,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
191610,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117
187375,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370
80444,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
211382,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769
219739,To Kill a Mockingbird,510,4.700000
183571,The Da Vinci Code,898,4.642539
187878,The Five People You Meet in Heaven,430,4.551163
180555,The Catcher in the Rye,449,4.545657
204670,"The Return of the King (The Lord of the Rings,...",211,4.497630
196324,The Lovely Bones: A Novel,1295,4.468726
190079,The Great Gatsby,205,4.458537
764,1984,284,4.454225
144164,Prodigal Summer: A Novel,253,4.450593
128669,Neverwhere,265,4.449057
206500,The Secret Life of Bees,774,4.447028
168718,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890
223133,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970
204385,The Red Tent (Bestselling Backlist),723,4.334716
27294,Brave New World,226,4.331858
191587,The Hitchhiker's Guide to the Galaxy,268,4.328358
129378,Nickel and Dimed: On (Not) Getting By in America,335,4.289552
209776,The Tao of Pooh,211,4.289100
14606,Animal Farm,233,4.274678
93380,Into the Wild,252,4.273810
63866,Fahrenheit 451,409,4.264059
7373,A Walk in the Woods: Rediscovering America on ...,205,4.243902
74749,Girl with a Pearl Earring,526,4.218631
129443,Night,202,4.217822
136144,Outlander,283,4.173145
209207,"The Subtle Knife (His Dark Materials, Book 2)",225,4.124444
181698,The Color of Water: A Black Man's Tribute to H...,223,4.107623
233367,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983
156101,Seabiscuit: An American Legend,275,4.098182
107961,Life of Pi,664,4.088855
176844,The Bean Trees,389,4.087404
2281,"A Child Called \It\"": One Child's Courage to S...",265,4.086792
8433,ANGELA'S ASHES,279,4.075269
83431,High Fidelity,247,4.056680
76342,Good in Bed,490,4.055102
64930,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383
12699,American Gods,302,4.006623
161644,Skipping Christmas,322,4.006211
105776,Left Behind: A Novel of the Earth's Last Days ...,318,4.003145
189549,"The Golden Compass (His Dark Materials, Book 1)",336,4.000000

In [33]:
Popular_books_final_with_info = Popular_books_final.merge(Books,on='Book-Title').drop_duplicates()[['Book-Title','Book-Author','Year-Of-Publication','Publisher','Image-URL-M','NumberOfRatings','AverageRating']]
Popular_books_final_with_info.drop_duplicates(subset='Book-Title',inplace=True)
Popular_books_final_with_info

,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-M,NumberOfRatings,AverageRating
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,1999,Scholastic,http://images.amazon.com/images/P/0439136350.0...,428,5.852804
3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439139597.0...,387,5.824289
5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,1998,Scholastic,http://images.amazon.com/images/P/0590353403.0...,278,5.737410
9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,2003,Scholastic,http://images.amazon.com/images/P/043935806X.0...,347,5.501441
13,Ender's Game (Ender Wiggins Saga (Paperback)),Orson Scott Card,1992,Tor Books,http://images.amazon.com/images/P/0312853238.0...,249,5.409639
17,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439064872.0...,556,5.183453
20,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,1986,Del Rey,http://images.amazon.com/images/P/0345339681.0...,281,5.007117
21,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,1986,Del Rey,http://images.amazon.com/images/P/0345339703.0...,368,4.948370
30,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,1999,Arthur A. Levine Books,http://images.amazon.com/images/P/059035342X.0...,575,4.895652
32,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,1986,Del Rey,http://images.amazon.com/images/P/0345339711.0...,260,4.880769
43,To Kill a Mockingbird,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,510,4.700000
51,The Da Vinci Code,Dan Brown,2003,Doubleday,http://images.amazon.com/images/P/0385504209.0...,898,4.642539
57,The Five People You Meet in Heaven,Mitch Albom,2003,Hyperion,http://images.amazon.com/images/P/0786868716.0...,430,4.551163
59,The Catcher in the Rye,J.D. Salinger,1991,"Little, Brown",http://images.amazon.com/images/P/0316769487.0...,449,4.545657
66,"The Return of the King (The Lord of the Rings,...",J.R.R. TOLKIEN,1986,Del Rey,http://images.amazon.com/images/P/0345339738.0...,211,4.497630
76,The Lovely Bones: A Novel,Alice Sebold,2002,"Little, Brown",http://images.amazon.com/images/P/0316666343.0...,1295,4.468726
77,The Great Gatsby,F. Scott Fitzgerald,1999,Lb May &amp; Assoc Inc,http://images.amazon.com/images/P/185326041X.0...,205,4.458537
79,1984,George Orwell,1990,Signet Book,http://images.amazon.com/images/P/0451524934.0...,284,4.454225
88,Prodigal Summer: A Novel,Barbara Kingsolver,2001,Perennial,http://images.amazon.com/images/P/0060959037.0...,253,4.450593
89,Neverwhere,Neil Gaiman,1998,Avon,http://images.amazon.com/images/P/0380789019.0...,265,4.449057
94,The Secret Life of Bees,Sue Monk Kidd,2003,Penguin Books,http://images.amazon.com/images/P/0142001740.0...,774,4.447028
100,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,2002,Regan Books,http://images.amazon.com/images/P/0060392452.0...,283,4.356890
101,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,1997,Doubleday,http://images.amazon.com/images/P/0385484518.0...,493,4.354970
104,The Red Tent (Bestselling Backlist),Anita Diamant,1998,Picador USA,http://images.amazon.com/images/P/0312195516.0...,723,4.334716
105,Brave New World,Aldous Huxley,1989,Harpercollins,http://images.amazon.com/images/P/0060809833.0...,226,4.331858
110,The Hitchhiker's Guide to the Galaxy,Douglas Adams,1982,Pocket,http://images.amazon.com/images/P/0671461494.0...,268,4.328358
119,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,2002,Owl Books,http://images.amazon.com/images/P/0805063897.0...,335,4.289552
121,The Tao of Pooh,Benjamin Hoff,1983,Penguin Books,http://images.amazon.com/images/P/0140067477.0...,211,4.289100
123,Animal Farm,George Orwell,2004,Signet,http://images.amazon.com/images/P/0451526341.0...,233,4.274678
133,Into the Wild,Jon Krakauer,1997,Anchor,http://images.amazon.com/images/P/0385486804.0...,252,4.273810
136,Fahrenheit 451,Ray Bradbury,1994,Distribooks Inc,http://images.amazon.com/images/P/3257208626.0...,409,4.264059
149,A Walk in the Woods: Rediscovering America on ...,Bill Bryson,1999,Broadway Books,http://images.amazon.com/images/P/0767902521.0...,205,4.243902
150,Girl with a Pearl Earring,Tracy Chevalier,2001,Plume Books,http://images.amazon.com/images/P/0452282152.0...,526,4.218631
151,Night,Elie Wiesel,1982,Bantam Books,http://images.amazon.com/images/P/0553272535.0...,202,4.217822
156,Outlander,DIANA GABALDON,1996,Dell,http://images.amazon.com/images/P/0440222915.0...,283,4.173145
162,"The Subtle Knife (His Dark Materials, Book 2)",PHILIP PULLMAN,2002,Knopf Books for Young Readers,http://images.amazon.com/images/P/0375823468.0...,225,4.124444
170,The Color of Water: A Black Man's Tribute to H...,James McBride,1997,Riverhead Books,http://images.amazon.com/images/P/1573225789.0...,223,4.107623
172,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,1998,Warner Books,http://images.amazon.com/images/P/0446672211.0...,585,4.105983
173,Seabiscuit: An American Legend,LAURA HILLENBRAND,2002,Ballantine Books,http://images.amazon.com/images/P/0449005615.0...,275,4.098182
175,Life of Pi,Yann Martel,2002,Harcourt,http://images.amazon.com/images/P/0151008116.0...,664,4.088855
179,The Bean Trees,Barbara Kingsolver,1989,Perennial,http://images.amazon.com/images/P/0060915544.0...,389,4.087404
182,"A Child Called \It\"": One Child's Courage to S...",Dave Pelzer,1995,Health Communications,http://images.amazon.com/images/P/1558743669.0...,265,4.086792
184,ANGELA'S ASHES,Frank McCourt,1996,Scribner,http://images.amazon.com/images/P/0684874350.0...,279,4.075269
186,High Fidelity,Nick Hornby,1996,Riverhead Books,http://images.amazon.com/images/P/1573225517.0...,247,4.056680
192,Good in Bed,Jennifer Weiner,2002,Washington Square Press,http://images.amazon.com/images/P/0743418174.0...,490,4.055102
194,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,2002,Perennial,http://images.amazon.com/images/P/0060938455.0...,321,4.037383
195,American Gods,Neil Gaiman,2002,HarperTorch,http://images.amazon.com/images/P/0380789035.0...,302,4.006623
196,Skipping Christmas,JOHN GRISHAM,2001,Doubleday,http://images.amazon.com/images/P/0385505833.0...,322,4.006211
202,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,1996,Tyndale House Publishers,http://images.amazon.com/images/P/0842329129.0...,318,4.003145
204,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,2002,Knopf Books for Young Readers,http://images.amazon.com/images/P/037582345X.0...,336,4.000000

In [34]:
import pickle
pickle.dump(Popular_books_final_with_info,open('Popular_books_final_with_info.pkl','wb'))

### Collaborative filtering approach

In [20]:
x = Ratings_with_bookinfo.groupby('User-ID').count()['Book-Rating'] > 200
educated_users = x[x].index

In [21]:
Y = Ratings_with_bookinfo[Ratings_with_bookinfo['User-ID'].isin(educated_users)]
Y

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-M
1150,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...
1151,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...
1152,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...
1153,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...
1154,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.0...
...,...,...,...,...,...,...,...,...
1029353,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA),http://images.amazon.com/images/P/1931868123.0...
1029354,275970,3411086211,10,Die Biene.,Sybil GrÃ?Â¤fin SchÃ?Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.0...
1029355,275970,3829021860,0,The Penis Book,Joseph Cohen,1999,Konemann,http://images.amazon.com/images/P/3829021860.0...
1029356,275970,4770019572,0,Musashi,Eiji Yoshikawa,1995,Kodansha International (JPN),http://images.amazon.com/images/P/4770019572.0...
1029357,275970,9626340762,8,Northanger Abbey (Classic Literature with Clas...,Jane Austen,1996,Naxos Audiobooks Ltd.,http://images.amazon.com/images/P/9626340762.0...

In [22]:
X = Y.groupby(by='Book-Title').count()['Book-Rating']>=50
X[X]

Book-Title
1984                                                                 True
1st to Die: A Novel                                                  True
2nd Chance                                                           True
4 Blondes                                                            True
A Bend in the Road                                                   True
                                                                     ...
Year of Wonders                                                      True
You Belong To Me                                                     True
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values    True
Zoya                                                                 True
\O\" Is for Outlaw"                                                  True
Name: Book-Rating, Length: 706, dtype: bool

In [23]:
rated_books = X[X].index
rated_books

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Day Late and a Dollar Short', 'A Fine Balance',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='Book-Title', length=706)

In [24]:
Final_rating = Y[Y['Book-Title'].isin(rated_books)]
Final_rating

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-M
1150,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...
1163,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...
1165,277427,0060934417,0,Bel Canto: A Novel,Ann Patchett,2002,Perennial,http://images.amazon.com/images/P/0060934417.0...
1168,277427,0061009059,9,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,1995,HarperTorch,http://images.amazon.com/images/P/0061009059.0...
1174,277427,006440188X,0,The Secret Garden,Frances Hodgson Burnett,1998,HarperTrophy,http://images.amazon.com/images/P/006440188X.0...
...,...,...,...,...,...,...,...,...
1029192,275970,1400031354,0,Tears of the Giraffe (No.1 Ladies Detective Ag...,Alexander McCall Smith,2002,Anchor,http://images.amazon.com/images/P/1400031354.0...
1029193,275970,1400031362,0,Morality for Beautiful Girls (No.1 Ladies Dete...,Alexander McCall Smith,2002,Anchor,http://images.amazon.com/images/P/1400031362.0...
1029266,275970,1573229725,0,Fingersmith,Sarah Waters,2002,Riverhead Books,http://images.amazon.com/images/P/1573229725.0...
1029305,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...
1029306,275970,1586212230,0,Naked,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586212230.0...

In [25]:
table = Final_rating.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')
table

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Bend in the Road,0.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,9.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN

In [26]:
table.fillna(0,inplace=True)

In [27]:
from sklearn.metrics.pairwise import cosine_similarity

In [28]:
Similarity_score = cosine_similarity(table)
print(Similarity_score.shape)
Similarity_score

(706, 706)

array([[1.        , 0.10255025, 0.01220856, ..., 0.12110367, 0.07347567,
        0.04316046],
       [0.10255025, 1.        , 0.2364573 , ..., 0.07446129, 0.16773875,
        0.14263397],
       [0.01220856, 0.2364573 , 1.        , ..., 0.04558758, 0.04938579,
        0.10796119],
       ...,
       [0.12110367, 0.07446129, 0.04558758, ..., 1.        , 0.07085128,
        0.0196177 ],
       [0.07347567, 0.16773875, 0.04938579, ..., 0.07085128, 1.        ,
        0.10602962],
       [0.04316046, 0.14263397, 0.10796119, ..., 0.0196177 , 0.10602962,
        1.        ]])

In [29]:
def recommend(book_name):
    index =  np.where(table.index == book_name )[0][0]
    similar_books = sorted(list(enumerate(Similarity_score[index])),key=lambda x:x[1],reverse=True)[1:8]
    
    for i in similar_books:
        print(table.index[i[0]])

In [30]:
recommend('1984')

Animal Farm
The Handmaid's Tale
Brave New World
The Vampire Lestat (Vampire Chronicles, Book II)
The Hours : A Novel
Fahrenheit 451
The Catcher in the Rye